config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  get 'notices/detail'
  get 'grades/export' =>"grades#export"
  post 'grades/import' =>"grades#import"

  get 'courses/export' => "courses#export"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :timetable
      get :swap
      get :select
      get :visitor
      get :quit
      get :open
      get :close
      get :show_more_4
      get :show_more_3
      get :show_more_2
      get :show_more_1
      get :open_visit
      get :close_visit
      get :selected
      get :chart
      get :semester
      get :apply
      get :advise
    end
    collection do
      get :list
      post :list
    end
  end

  resources :grades, only: [:index, :update]
  resources :users
  resources :emails do
    member do
      post :create
    end
  end
  resources :comments do
    member do
      get :semester
    end
    collection do
      get :list
    end
  end

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

  before_action :teacher_logged_in, only: [:update]

  def update
    @grade=Grade.find_by_id(params[:id])
    if @grade.update_attributes!(:grade => params[:grade][:grade])
      flash={:success => "#{@grade.user.name} #{@grade.course.name}的成绩已成功修改为 #{@grade.grade}"}
    else
      flash={:danger => "上传失败.请重试"}
    end
    redirect_to grades_path(course_id: params[:course_id]), flash: flash
  end

  def index
    if teacher_logged_in?
      @course=Course.find_by_id(params[:course_id])
      @grades=@course.grades.where(:open=>false)
    elsif student_logged_in?
      @grades=current_user.grades
    else
      redirect_to root_path, flash: {:warning=>"请先登录"}
    end
  end

  def import
    file = params[:file]
    begin
      file_ext = File.extname(file.original_filename)
      if not [".xls", ".xlsx"].include?(file_ext)
        flash={:danger => "失败，文件类型不支持"}
      else
        spreadsheet = (file_ext == ".xls") ? Roo::Excel.new(file.path) : Roo::Excelx.new(file.path)
        header = spreadsheet.row(1)
        (2..spreadsheet.last_row).each do |i|
          @grade=Grade.find_by_id(spreadsheet.row(i)[0])
          @grade.update_attributes!(:grade => spreadsheet.row(i)[6])
        end
        flash={:success => "上传成功"}
      end
      redirect_to grades_path(course_id: params[:course_id]), flash: flash
    end
  end

  def export
    if teacher_logged_in?
      @course=Course.find_by_id(params[:course_id])
      @grades=@course.grades
    else
      redirect_to root_path, flash: {:warning=>"请先登录"}
    end

    respond_to do |format|
      format.html
      format.xls {
        require 'spreadsheet'
        book = Spreadsheet::Workbook.new
        sheet1 = book.create_worksheet
        sheet1.row(0).concat %w{成绩id 学号 姓名 专业 培养单位 课程 成绩}
        @grades.each_with_index do |grade,i|
          #puts(grade.user.num)
          sheet1.row(i+1).push grade.id, grade.user.num, grade.user.name, grade.user.major, grade.user.department, grade.course.name, grade.grade
        end
        book.write 'wqs.xls'
        send_file 'wqs.xls',:type => "application/vnd.ms-excel", :filename => "#{@course.name}.xls", :stream => false
        return
      }
    end
  end

  private

  # Confirms a teacher logged-in user.
  def teacher_logged_in
    unless teacher_logged_in?
      redirect_to root_url, flash: {danger: '请登录'}
    end
  end

end

app/views/grades/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <%= render "shared/sidenav" %>

    </div>
    <div class="col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <% if teacher_logged_in? %><h3 class="panel-title">成绩管理: <%=@course.name%></h3><% end %>
          <% if student_logged_in? %><h3 class="panel-title">成绩列表</h3><% end %>
        </div>
        <div class="panel-body" style="min-height: 450px">
        <% if teacher_logged_in? %>
            <div class="row">
              <div class="col-sm-12" style="padding-bottom: 26px">
                <%= form_tag 'grades/import', multipart: true do %>
                    <div class="file_style">
                      <input type="hidden" value="<%= @course.id %>" name="course_id">
                      <input type='text' name='textfield' id='textfield' class="fileText">
                      <input type='button' class='btn btn-success btn-xs' value='浏览'>
                      <%= file_field_tag :file, :class => "fileInput", :size => "28", :onchange => "document.getElementById('textfield').value=this.value" %>
                      <%= submit_tag "上传", :class => "btn btn-success btn-xs" %>
                      <%= link_to "导出", grades_export_url(:course_id => @course.id, :format => 'xls'), :class => "btn btn-success btn-xs" %>
                    </div>
                <% end %>
              </div>
            </div>
        <% end %>

          <table class="table table-striped table-hover">
            <thead>

            <tr>
              <th>课程编号</th>

              <th>学期</th>
              <% if teacher_logged_in? %>
              <th>学生</th>
              <% end %>
              <% if student_logged_in? %>
                  <th>教师</th>
              <% end %>
              <th>课程</th>
              <th>分数</th>

            </tr>
            </thead>
            <tbody>

            <% @grades.each do |grade| %>
                <tr>
                  <td><%= grade.course.course_code %></td>

                  <td><%= grade.course.semester.info %></td>
                  <% if student_logged_in? %>
                  <td><%= grade.course.teacher.name %></td>
                  <% end %>
                  <% if teacher_logged_in? %>
                      <td><%= grade.user.name %></td>
                  <% end %>
                  <td><%= grade.course.name %></td>
                  <td><%= grade.grade %></td>

                  <% if teacher_logged_in? %>
                      <%= form_for grade, url: grade_url(id: grade.id, course_id: grade.course.id), method: :patch do |f| %>
                          <td><%= f.text_field :grade %></td>
                          <td><%= f.submit "提交", class: "btn btn-success btn-xs" %></td>
                      <% end %>
                  <% end %>

                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>


