config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  get 'notices/detail'
  get 'grades/export' =>"grades#export"
  post 'grades/import' =>"grades#import"

  get 'courses/export' => "courses#export"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :timetable
      get :swap
      get :select
      get :visitor
      get :quit
      get :open
      get :close
      get :show_more_4
      get :show_more_3
      get :show_more_2
      get :show_more_1
      get :open_visit
      get :close_visit
      get :selected
      get :chart
      get :semester
      get :apply
      get :advise
    end
    collection do
      get :list
      post :list
    end
  end

  resources :grades, only: [:index, :update]
  resources :users
  resources :emails do
    member do
      post :create
    end
  end
  resources :comments do
    member do
      get :semester
    end
    collection do
      get :list
    end
  end

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def semester
    @course = current_user.teaching_courses.where(semester: params[:id])
  end

  def edit
    @comment=Comment.find_by_id(params[:id])
  end

  def update
    @comment = Comment.find_by_id(params[:id])
    if @comment.update_attributes(comment_params)
      @comment.commented = true
      if @comment.save
        flash={:success => "#{@comment.course.name}已评估"}
        redirect_to comments_path, flash: flash
      else
        flash={:info => "评估失败"}
        redirect_to edit_comment_path, flash: flash
      end
    else
      flash={:warning => "评估失败"}
      redirect_to edit_comment_path, flash: flash
    end
  end

  def list
    @course=Course.find_by_id(params[:course_id])
    @comments=@course.comments
    @comments_score = Array[0,0,0,0,0]
    @comments_count = Array[0,0,0,0,0]
    @comments.each do |comment|
      if !(comment.item_one.nil?) then
        @comments_count[0]+=1
        @comments_score[0] += comment.item_one
      end
      if !(comment.item_two.nil?) then
        @comments_count[1]+=1
        @comments_score[1] += comment.item_two
      end
      if !(comment.item_three.nil?) then
        @comments_count[2]+=1
        @comments_score[2] += comment.item_three
      end
      if !(comment.item_four.nil?) then
        @comments_count[3]+=1
        @comments_score[3] += comment.item_four
      end
      if !(comment.item_five.nil?) then
        @comments_count[4]+=1
        @comments_score[4] += comment.item_five
      end

    end
      @i = 0
      @i_count = 0
      @comments_score_sum = 0
      while @i < 5 do
        if  @comments_count[@i] > 0then
          @i_count+=1
        @comments_score[@i] /=  @comments_count[@i]
        @comments_score_sum += @comments_score[@i]
        end
        @i+=1
      end
    if @i_count > 0
     @comments_score_sum /= @i_count
     @course.update_attributes(:course_score=>@comments_score_sum)
      end
  end

  def index
    @courses=current_user.courses if student_logged_in?
    @comments=current_user.comments if student_logged_in?
    @course=current_user.teaching_courses if teacher_logged_in?
    @comments=@course.comments if teacher_logged_in?
  end

  # Confirms a student logged-in user.
  def student_logged_in
    unless student_logged_in?
      redirect_to root_url, flash: {danger: '请登录'}
    end
  end

  # Confirms a teacher logged-in user.
  def teacher_logged_in
    unless teacher_logged_in?
      redirect_to root_url, flash: {danger: '请登录'}
    end
  end

  # Confirms a  logged-in user.
  def logged_in
    unless logged_in?
      redirect_to root_url, flash: {danger: '请登录'}
    end
  end

  def course_params
    params.require(:course).permit(:course_code, :name, :course_type, :teaching_type, :exam_type,
                                   :credit, :limit_num, :class_room, :course_time, :course_week)
  end
  def comment_params
    params.require(:comment).permit(:item_one, :item_two, :item_three, :item_four, :item_five,:item_six,
                                    :item_seven, :item_eight, :item_nine, :item_ten, :item_eleven,:item_twelve,
                                    :item_thirteen,:item_fourteen,:item_fifteen,:item_sixteen,:item_seventeen,
                                    :comment_advantage,:comment_disadvantage)
  end
end

app/views/comments/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <%= render "shared/sidenav" %>

    </div>
    <div class="col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">评估课程:<%=@comment.course.name%></h3>
        </div>
        <div class="panel-body" style="min-height: 450px">
          <table class="table table-striped table-bordered table-advance table-hover">
            当前评估课程：<label style="color:red;"><%=@comment.course.name%></label>&nbsp&nbsp&nbsp主讲教师：<lable style="color:red;"><%=@comment.course.teacher.name%></lable>&nbsp&nbsp&nbsp&nbsp所属院系：<lable style="color:red;"><%=@comment.course.teacher.department%></lable>
            </br> </br>
            <thead>
            <tr>
              <th class="active">序号</th>
              <th class="active">评估内容</th>
              <th class="active">评分</th>
            </tr>
            </thead>
            <%= form_for @comment,html: {class: 'form-horizontal', role: 'form'} do |f| %>
                <%= render 'shared/error_messages', :object => @comment %>
                <tbody>
                <tr>
                  <th class="success">1</th>
                  <th class="success">治学严整、言传身教</th>
                  <td>
                    <span style="margin-left: 10px"><%= f.radio_button :item_one, 100 %><%= label_tag("优") %></span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_one, 80 %><%= label_tag("良") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_one, 60 %><%= label_tag("中") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_one, 40 %><%= label_tag("差") %> </span>
                    <span style="margin-left: 10px" ><%= f.radio_button :item_one, 20 %><%= label_tag("极差") %> </span>
                  </td>
                </tr>
                <tr>
                  <th class="success">2</th>
                  <th class="success">备课充分，讲课认真</th>
                  <td>
                    <span style="margin-left: 10px"><%= f.radio_button :item_two, 100 %><%= label_tag("优") %></span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_two, 80 %><%= label_tag("良") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_two, 60 %><%= label_tag("中") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_two, 40 %><%= label_tag("差") %> </span>
                    <span style="margin-left: 10px" ><%= f.radio_button :item_two, 20 %><%= label_tag("极差") %> </span>
                  </td>
                </tr>
                <tr>
                  <th class="success">3</th>
                  <th class="success">仪装端庄，精神饱满 </th>
                  <td>
                    <span style="margin-left: 10px"><%= f.radio_button :item_three, 100 %><%= label_tag("优") %></span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_three, 80 %><%= label_tag("良") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_three, 60 %><%= label_tag("中") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_three, 40 %><%= label_tag("差") %> </span>
                    <span style="margin-left: 10px" ><%= f.radio_button :item_three, 20 %><%= label_tag("极差") %> </span>
                  </td>
                </tr>
                <tr>
                  <th class="success">4</th>
                  <th class="success">虚心听取意见，积极改进教学</th>
                  <td>
                    <span style="margin-left: 10px"><%= f.radio_button :item_four, 100 %><%= label_tag("优") %></span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_four, 80 %><%= label_tag("良") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_four, 60 %><%= label_tag("中") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_four, 40 %><%= label_tag("差") %> </span>
                    <span style="margin-left: 10px" ><%= f.radio_button :item_four, 20 %><%= label_tag("极差") %> </span>
                  </td>
                </tr>
                <tr>
                  <th class="success">5</th>
                  <th class="success">无调课、停课、替讲现象</th>
                  <td>
                    <span style="margin-left: 10px"><%= f.radio_button :item_five, 100 %><%= label_tag("优") %></span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_five, 80 %><%= label_tag("良") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_five, 60 %><%= label_tag("中") %> </span>
                    <span style="margin-left: 10px"><%= f.radio_button :item_five, 40 %><%= label_tag("差") %> </span>
                    <span style="margin-left: 10px" ><%= f.radio_button :item_five, 20 %><%= label_tag("极差") %> </span>
                  </td>
                </tr>

                </tbody>
                </table>
                <div class="control-group">
                  <h4>本课程的优点：</h4>
                </div>
                <div class="control-group">
                  <div class="controls2">
                    <%= f.text_area :comment_advantage, class: 'form-control' %>
                  </div>
                </div>
                <div class="control-group">
                  <h4>本课程的缺点：</h4>
                </div>
                <div class="control-group">
                  <div class="controls2">
                    <%= f.text_area :comment_disadvantage, class: 'form-control' %>
                  </div>
                </div>
                <h3></h3>
                <div class="form-actions">
                  <%if !@comment.commented? %>
                      <%= f.submit "提交", :class => "btn btn-default btn-block" %>
                      <%else%>
                      <%= f.submit "修改", :class => "btn btn-default btn-block" %>
                  <%end%>
                      <%= link_to '取消', comments_path, :class => "btn btn-default btn-block" %>
                </div>

            <%end%>
            </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  var   getURL   =   window.location.href;
  var   index     =   getURL.indexOf( "?reload=no ");
  if   (  location.href.indexOf('#reloaded')==-1 && location.href.endsWith("edit") ){
    location.href=location.href+"#reloaded"
    location.reload()
    setTimeout(function(){window.location.href=url},0)
  }
</script>

app/views/comments/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <%= render "shared/sidenav" %>
    </div>

    <div class="col-sm-10">

      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <% if teacher_logged_in? %><h3 class="panel-title">评估结果</h3><% end %>
          <% if student_logged_in? %><h3 class="panel-title">课程评估</h3><% end %>
        </div>

        <div class="panel-body">
          <table class="table table-responsive table-condensed table-hover">
            <thead>
            <tr>
              <th>课程编号</th>
              <th>课程名称</th>
              <th>课时/学分</th>
              <th>考试方式</th>
              <th>主讲教师</th>
              <th></th>
            </tr>

            <tbody>
            <% @comments.each do |comment| %>
                <tr>
                  <td><%= comment.course.course_code %></td>
                  <td><%= comment.course.name %></td>
                  <td><%= comment.course.credit %></td>
                  <td><%= comment.course.exam_type %></td>
                  <td><%= comment.course.teacher.name %></td>
                  <%if comment.commented?%>
                      <td><%= link_to "修改评估", edit_comment_url(comment), class: 'btn btn-xs btn-info' %></td>
                  <% end %>
                  <%if !comment.commented?%>
                      <td><%= link_to "评估", edit_comment_url(comment), class: 'btn-sm btn-success' %></td>
                  <% end %>
                </tr>
            <% end %>
            </tbody>
          </table>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/list.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <%= render "shared/sidenav" %>
    </div>

    <div class="col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">课程名称: <%=@course.name%></h3>
        </div>
        <div class="panel-body" >
          <table class="table table-striped table-bordered ">
            <thead>
            <tr>
              <th>评估内容</th>
              <th>评分(平均值/人次)</th>

            </tr>
            </thead>

            <tbody>
            <tr>
              <th>治学严整、言传身教</th>
              <td>
                <%= @comments_score[0]%> / <%= @comments_count[0]%>
              </td>
              <!--<th>备课充分，讲课认真</th>
              <td>
                <%= @comments_score[1] %> / <%= @comments_count[1]%>
              </td>-->
            </tr>
            <tr>
              <th>备课充分，讲课认真</th>
              <td>
                <%= @comments_score[1] %> / <%= @comments_count[1]%>
              </td>
            </tr>
            <tr>
              <th>仪装端庄，精神饱满 </th>
              <td>
                <%= @comments_score[2] %> / <%= @comments_count[2]%>
              </td>

            </tr>
            <tr>
              <th>虚心听取意见，积极改进教学</th>
              <td>
                <%= @comments_score[3] %> / <%= @comments_count[3]%>
              </td>
            </tr>
            <tr>
              <th>无调课、停课、替讲现象</th>
              <td>
                <%= @comments_score[4] %> / <%= @comments_count[4]%>
              </td>

            <tr>

              <th>课程综合得分为：</th>
              <td>
                <%= @comments_score_sum %>
              </td>
            </tr>
            </tbody>
          </table>
          <div class="panel panel-primary filterable">
            <div class="panel-heading btn_new">
              本课程的优势所在：
            </div>
            <div class="table-responsive">
              <table class="table table-striped" id="curriculum_table">
                <tbody>
                <% @comments.each do |comment| %>
                    <% if !(comment.comment_advantage.nil?)%>
                        <tr>
                          <th><%= comment.comment_advantage %></th>
                        </tr>
                    <% end %>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <div class="panel panel-primary filterable">
            <div class="panel-heading btn_new">
              本课程的劣势所在：
            </div>
            <div class="table-responsive">
              <table class="table table-striped" id="curriculum_table">
                <tbody>
                <% @comments.each do |comment| %>
                    <% if !(comment.comment_disadvantage.nil?)%>
                        <tr>
                          <th><%= comment.comment_disadvantage %></th>
                        </tr>
                    <% end %>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/semester.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-sm-2">
      <%= render "shared/sidenav" %>
    </div>

    <div class="col-sm-10">

      <div class="panel panel-primary filterable">
        <div class="panel-heading">
          <% if teacher_logged_in? %><h3 class="panel-title">授课列表</h3><% end %>
          <% if student_logged_in? %><h3 class="panel-title">已选课程</h3><% end %>
        </div>

        <div class="panel-body">
          <table class="table table-responsive table-condensed table-hover">
            <thead>
            <tr>
              <th>课程编号</th>
              <th>课程名称</th>
              <th>课时/学分</th>
              <th>考试方式</th>
              <th>主讲教师</th>
              <th>选课情况</th>
              <th></th>
            </tr>

            <tbody>
            <% @course.each do |course| %>
                <tr>

                  <td><%= course.course_code %></td>
                  <td><%= course.name %></td>
                  <td><%= course.credit %></td>
                  <td><%= course.exam_type %></td>
                  <td><%= course.teacher.name %></td>

                  <% if teacher_logged_in? %>
                      <td><%= link_to "选课情况", selected_course_url(course), class: 'btn btn-xs btn-info' %></td>
                      <td><%= link_to "查看结果", list_comments_path(course_id: course.id),  class: 'btn btn-xs btn-success' %></td>
                  <% end %>
                </tr>
            <% end %>
            </tbody>
          </table>

        </div>
      </div>
    </div>
  </div>
</div>