config/routes.rb
Rails.application.routes.draw do
  get 'notices/index'
  get 'notices/detail'
  get 'grades/export' =>"grades#export"
  post 'grades/import' =>"grades#import"

  get 'courses/export' => "courses#export"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :timetable
      get :swap
      get :select
      get :visitor
      get :quit
      get :open
      get :close
      get :show_more_4
      get :show_more_3
      get :show_more_2
      get :show_more_1
      get :open_visit
      get :close_visit
      get :selected
      get :chart
      get :semester
      get :apply
      get :advise
    end
    collection do
      get :list
      post :list
    end
  end

  resources :grades, only: [:index, :update]
  resources :users
  resources :emails do
    member do
      post :create
    end
  end
  resources :comments do
    member do
      get :semester
    end
    collection do
      get :list
    end
  end

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_sidenav.html.erb
<div class="panel-group" id="accordion">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">

        <% if teacher_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#CourseCollapse"><span class="glyphicon glyphicon-user"></span>
              我的课程</a>
        <% end %>

        <% if student_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#CourseCollapse"><span class="glyphicon glyphicon-user"></span>
              本学期课程</a>
        <% end %>

      </h4>
    </div>

    <div id="CourseCollapse" class="panel-collapse collapse <%= "in" if ["courses"].include?(params[:controller]) %>">
      <ul class="list-group">
        <% if teacher_logged_in? %>
            <% Semester.all.each do | semester |%>
            <li class="list-group-item">
              <%= link_to semester_course_url(semester.id) do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> <%= semester.info %>
              <% end %>
            </li>
            <% end %>
            <li class="list-group-item">
              <%= link_to new_course_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 创建新课程
              <% end %>
            </li>
        <% end %>

        <% if student_logged_in? %>
            <li class="list-group-item">
              <%= link_to list_courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 可选课程
                  <span class="label label-info pull-right"><%= (Course.where(:open => true)-current_user.courses).length %></span>
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to courses_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 已选课程
                  <span class="label label-info pull-right"><%= current_user.courses.length %></span>
              <% end %>
            </li>
            <!jq++>
            <li class="list-group-item">
              <%= link_to timetable_course_url(current_user.courses) do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 个人课表
              <% end %>
            </li>
        <% end %>

      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <% if teacher_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#GradeCollapse"><span class="glyphicon glyphicon-user"></span>
              成绩管理</a>
        <% end %>

        <% if student_logged_in? %>
            <a data-toggle="collapse" data-parent="#accordion" href="#GradeCollapse"><span class="glyphicon glyphicon-user"></span>
              课程成绩</a>
        <% end %>
      </h4>
    </div>

    <div id="GradeCollapse" class="panel-collapse collapse <%= "in" if ["grades"].include?(params[:controller]) %>">
      <div class="list-group">

        <% if teacher_logged_in? %>
            <% current_user.teaching_courses.each do |course| %>
                <li class="list-group-item">
                  <%= link_to grades_path(course_id: course.id), :method => :get do %>
                      <span class="glyphicon glyphicon-chevron-right"></span> <%= course.name %>
                      <span class="label label-info pull-right"><%= course.grades.where(:open=>false).length %></span>
                  <% end %>
                </li>
            <% end %>

        <% end %>

        <% if student_logged_in? %>
            <li class="list-group-item">
              <%= link_to grades_path do %>
                  <span class="glyphicon glyphicon-chevron-right"></span> 所有成绩
              <% end %>
            </li>
        <% end %>

      </div>
    </div>
  </div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">

      <% if teacher_logged_in? %>
          <a data-toggle="collapse" data-parent="#accordion" href="#CommentCollapse"><span class="glyphicon glyphicon-user"></span>
            评估结果</a>
      <% end %>

      <% if student_logged_in? %>
          <a data-toggle="collapse" data-parent="#accordion" href="#CommentCollapse"><span class="glyphicon glyphicon-user"></span>
            课程评估</a>
      <% end %>

    </h4>
  </div>

  <div id="CommentCollapse" class="panel-collapse collapse <%= "in" if ["comments"].include?(params[:controller]) %>">
    <ul class="list-group">
      <% if teacher_logged_in? %>
          <% Semester.all.each do | semester |%>
              <li class="list-group-item">
                <%= link_to semester_comment_url(semester.id), :method => :get do %>
                    <span class="glyphicon glyphicon-chevron-right"></span> <%= semester.info %>
                <% end %>
              </li>
          <% end %>
      <% end %>

      <% if student_logged_in? %>

          <li class="list-group-item">
            <%= link_to comments_path do %>
                <span class="glyphicon glyphicon-chevron-right"></span> 所有课程
                <span class="label label-info pull-right"><%= current_user.courses.length %></span>
            <% end %>
          </li>
      <% end %>

    </ul>
  </div>
</div>
</div>